## 라이브러리 설치

In [1]:
!pip install numpy

In [2]:
import numpy as np

print(np.__version__)

2.1.1


In [4]:
# help(np)

In [5]:
num1 = [1, 2, 3]
num2 = [4, 5, 6]
#       5, 6, 7
num1 + num2 

[1, 2, 3, 4, 5, 6]

In [7]:
num1_arr =np.array(num1)
num2_arr =np.array(num2)

num1_arr + num2_arr

array([5, 7, 9])

In [8]:
print(type(num1_arr))
# 속성 ,메서드 

<class 'numpy.ndarray'>


In [10]:
num1_arr.data

In [11]:
num1_arr.dtype # 해당되는배열의 데이터 타입을 출력

dtype('int64')

In [12]:
num1_arr.shape

(3,)

In [13]:
num1_arr.ndim

1

In [14]:
num1_arr.max()

np.int64(3)

# 배열
0~1000000

In [15]:
num1_arr = np.array(num1, dtype="int8")
num1_arr.dtype

dtype('int8')

## 배열 만드는 방법

In [16]:
# 기본적으로  다른 데이터 자료형으로 numpy  배열로 변환
# 배열 생성
print(np.ones(3))


[1. 1. 1.]


In [18]:
print(np.zeros(5))

[0. 0. 0. 0. 0.]


In [22]:
# 1차원, 2차원 ,3차원,4차원
print(np.ndarray(shape=(2,2,2),dtype=float, order ='F'))


[[[6.23042070e-307 2.67020135e-306]
  [1.69121096e-306 1.78019082e-306]]

 [[4.67296746e-307 1.42413555e-306]
  [3.22646744e-307 1.37959740e-306]]]


In [26]:
arr = np.ndarray(shape=(2,2,2),dtype=float, order ='F')
arr.shape

(2, 2, 2)

# 배열의 차원을 변경

In [32]:
temp_arr = np.arange(16)
temp_arr.reshape(1,2,8)

array([[[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15]]])

In [33]:
temp_arr = np.arange(16)
temp_arr.reshape(2,2,8)

ValueError: cannot reshape array of size 16 into shape (2,2,8)

In [34]:
a16 = np.array([1.333333], dtype = np.float16)
a32 = np.array([1.333333], dtype = np.float32)

print(a16)
print(a32)

[1.333]
[1.333333]


In [35]:
arr =np.array([-1,2,-3])
arr/0

C:\Users\campus3S005\AppData\Local\Temp\ipykernel_9368\3226697582.py:2: RuntimeWarning: divide by zero encountered in divide
  arr/0


array([-inf,  inf, -inf])

## 결측치
- Missing values : 잃어버린 값
- nan : Not a Number, => 아직 정의되지 않은 숫자 의미

In [37]:
print(np.nan, type(np.nan))

nan <class 'float'>


In [40]:
print(np.inf, type(np.inf))

inf <class 'float'>


In [41]:
print(-np.inf, type(-np.inf))

-inf <class 'float'>


In [43]:
arr = np.array([-1,2,-3])
print(arr + np.nan)
print(arr + np.inf)

[nan nan nan]
[inf inf inf]


# 인덱싱 & 슬라이싱

In [45]:
arr = np.arange(10)
arr[1:5]

array([1, 2, 3, 4])

In [48]:
arr = np.arange(10).reshape(2,5)
arr[0] [1]

np.int64(1)

In [52]:
arr = np.arange(10000).reshape(100,100)
arr[0:4][0:1]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
        48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
        64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79,
        80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95,
        96, 97, 98, 99]])

In [54]:
arr = np.arange(4)
arr[:2]

array([0, 1])

In [89]:
arr = np.arange(20).reshape(4,5)
arr[1:4,2:5] 

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

In [91]:
# arr [행,열]
arr[1:,3:]

array([[ 8,  9],
       [13, 14],
       [18, 19]])

## 브로드캐스팅 연산

In [92]:
a = np.array([1,2,3])
             # 3.0 3.0 3.0
b = 3.0
a + b

array([4., 5., 6.])

## 조건 연산
- 원하는 결과값 : True/False

In [94]:
arr = np.array([10,20,30])
arr > 10

array([False,  True,  True])

In [95]:
arr = np.array([10,20,30])
cond = [False, True, True]

arr[cond]

array([20, 30])

In [97]:
arr = np.array([18,20,30,50,30,16])
cond = arr > 18
arr[cond]

array([20, 30, 50, 30])

In [99]:
arr = np.array([18,20,30,50,30,16])
arr[arr>18]

array([20, 30, 50, 30])

In [109]:
arr = np.array([18,20,30,50,30,16])
cond0 = arr > 18
cond1 = arr < 65


arr[cond1 & cond0 ]

array([20, 30, 50, 30])

In [110]:
arr[cond0 | cond1]

array([18, 20, 30, 50, 30, 16])

In [111]:
#권장사항, 이유 : pandas 다중조건 필터링
# () 반드시 필요
arr [(cond0 | cond1)]

array([18, 20, 30, 50, 30, 16])

## np.where

In [115]:
import numpy as np
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [116]:
np.where(a < 5 , a , 10*a)

array([ 0,  1,  2,  3,  4, 50, 60, 70, 80, 90])

# 함수와 메서드

In [124]:
arr =np.arange(8).reshape(2,4)
arr

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [121]:
arr.sum(axis = None)

np.int64(28)

In [125]:
arr.sum(axis = 0) # x축 방향으로 데이터의 합을 구하여라 행 단위

array([ 4,  6,  8, 10])

In [126]:
arr.sum(axis = 1) # Y축 방향으로 열 단위로 데이터의 합을 구하라

array([ 6, 22])

In [154]:
# 무작위 랜덤 함수 만들기
np.random.seed(42) # 머신러닝 할때 , 이코드를 자주 사용
np.random.randint(10)

6

In [155]:
np.random.randint(46, size=6) # 46 의미하는 것은 0~45번쨰까지의 숫자중 무작위로 가져오겠음

array([28, 14, 42,  7, 20, 38], dtype=int32)

In [169]:
np.random.randint(46, size=(3,4))

array([[18, 35, 11, 40],
       [18, 11,  8,  6],
       [27, 13, 30, 18]], dtype=int32)

In [180]:
x = np.linspace(0,100,11)
print(x)

[  0.  10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]


# Pandas Series

In [182]:
import pandas as pd
pd.__version__

'2.2.3'

In [183]:
data = [10, 20 , 30]
s = pd.Series(data)
s

0    10
1    20
2    30
dtype: int64

In [184]:
print(type(s))

<class 'pandas.core.series.Series'>


In [185]:
import numpy as np

data = np.arange(5)
s = pd.Series(data)
s

0    0
1    1
2    2
3    3
4    4
dtype: int64

In [190]:
import numpy as np

data = np.arange(5)
s = pd.DataFrame(data)
s

0
0  0
1  1
2  2
3  3
4  4

In [191]:
data = ["시가","고가"]
s = pd.Series(data)
s

0    시가
1    고가
dtype: object

In [192]:
data = [80000,"90000"]
s = pd.Series(data)
s

0    80000
1    90000
dtype: object

# 시리즈 인덱스

In [194]:
data = [1000, 2000, 3000]
s = pd.Series(data)
print(s.index, type(s.index))

RangeIndex(start=0, stop=3, step=1) <class 'pandas.core.indexes.range.RangeIndex'>


In [195]:
list(s.index) # 리스트로 형변환이 일어났다.

[0, 1, 2]

In [196]:
s.index.to_list() 

[0, 1, 2]

In [198]:
#help(s.index) #클래스에는 항상 속성과 메서드가 존재한다.

In [220]:
# 시리즈를 생성하면서 인덱스도 같이 생성 
data = [1000, 2000, 3000]
index = ["메로나","자두바","와"]

s = pd.Series(data=data,index=index)
s

메로나    1000
자두바    2000
와      3000
dtype: int64

In [221]:
s.values , type(s.values)

(array([1000, 2000, 3000]), numpy.ndarray)

## 시리즈 인덱싱 

In [222]:
print(s.iloc[2])

3000


In [223]:
print(s.loc['메로나'])

1000


In [242]:
# 시리즈를 생성하면서 인덱스도 같이 생성 
data = [1000, 2000, 3000]

s2= pd.Series(data=data)
print(s2.iloc[0])
print(s2,loc['메로나'])  #인덱스가 없어 에러가 난다 . 인덱스 기반으로 

1000


NameError: name 'loc' is not defined

In [232]:
print(s2.iloc[0]) #iloc 에서의 0은 위치 0을 의미
print(s2.loc[0]) #ioc 에서의 0은 라벨 0을 의미 초반에는 기본값은 loc라 생각해라 

1000
1000


# 슬라이싱

In [233]:
s

메로나    1000
자두바    2000
와      3000
dtype: int64

In [243]:
s.loc["메로나":"와"]

메로나    1000
자두바    2000
와      3000
dtype: int64

s2

In [245]:
s2.iloc[0:2]

0    1000
1    2000
dtype: int64

In [246]:
s2.loc[0:2]

0    1000
1    2000
2    3000
dtype: int64

## 시리즈 수정/추가/삭제

In [249]:
data = [1000, 2000, 3000]
index = ["메로나","자두바","와"]

s = pd.Series(data=data, index= index)

메로나    1000
자두바    2000
와      3000
dtype: int64

In [253]:
s.loc['메로나'] = 500 #가독성이 훨씬 좋음 
s

메로나     500
자두바    2000
와      3000
dtype: int64

# 시리즈 연산


In [255]:
import pandas as pd

evan = pd.Series([10, 20, 30], index=['NAVER','APPLE','엔비디아'])
딸1 = pd.Series([10, 30 , 20], index=["엔비디아","NAVER","APPLE"])

# 우리가족이 보유하고 있는 주식의 숫자를 계산
evan +딸1

APPLE    40
NAVER    40
엔비디아     40
dtype: int64

In [276]:
딸1

엔비디아     10
NAVER    30
APPLE    20
dtype: int64

In [292]:
evan + 딸1

APPLE    40.0
NAVER    40.0
엔비디아      NaN
테슬라       NaN
dtype: float64

In [278]:
evan = pd.Series([10, 20, 30], index=['NAVER','APPLE','테슬라'])
딸1 = pd.Series([10, 30 , 20], index=["엔비디아","NAVER","APPLE"])

# 우리가족이 보유하고 있는 주식의 숫자를 계산
evan +딸1

APPLE    40.0
NAVER    40.0
엔비디아      NaN
테슬라       NaN
dtype: float64

In [305]:
date = ["6/1", "6/2", "6/3", "6/4", "6/5"]
high =pd.Series([42800, 42700, 42050, 42950, 43000], index=date)
low =pd.Series([42150, 42150, 41300, 42150, 42350] , index=date)

diff = high - low
print(diff)

6/1    650
6/2    550
6/3    750
6/4    800
6/5    650
dtype: int64


In [310]:
diff.idxmax(), diff[diff.idxmax()]

('6/4', np.int64(800))

In [311]:
diff.idxmin(), diff[diff.idxmin()]

('6/2', np.int64(550))

In [313]:
profit = high/low #단순 수익률 계산
profit

6/1    1.015421
6/2    1.013049
6/3    1.018160
6/4    1.018980
6/5    1.015348
dtype: float64

In [314]:
profit.cumprod()

6/1    1.015421
6/2    1.028671
6/3    1.047351
6/4    1.067230
6/5    1.083610
dtype: float64

# 시리즈와 Map 

In [316]:
text = '1,234'
result = int(text.replace(',',''))
type(result),result

(int, 1234)

In [319]:
num_str= (['1,234','5,678','12,345'])  #판다스를 쓰지않고 원래의 문자열을 정수형을 바꾸는 
results = []
for num in num_str:
    temp = int(num.replace(',',''))
    results.append(temp)

results

[1234, 5678, 12345]

In [321]:
def rm_coma(x):
    return int(num.replace(',',''))

In [322]:
s = pd.Series(['1,234','5,678','12,345']) 
result =  s.map(rm_coma)
result

0    12345
1    12345
2    12345
dtype: int64

In [323]:
def remove_dollar_sign(x):
    return float(x.replace('$', '').replace(',', ''))
s = pd.Series(['$1,234.56', '$5,678.90', '$12,345.67'])
result = s.map(remove_dollar_sign)
result

0     1234.56
1     5678.90
2    12345.67
dtype: float64

## 문제
- 기준점이 13 이상
  + 크다 or 작다

In [330]:
def is_greater_13(x): 

    return_text = None
    if x >= 13:
        return "크다"
    else:
        return "작다" 

s = pd.Series([10, 15, 7, 20, 13])
s.map(is_greater_13)

0    작다
1    크다
2    작다
3    크다
4    크다
dtype: object

In [331]:
result = s.map(lambda x:'크다'if x >= 13 else '작다')
print(result)

0    작다
1    크다
2    작다
3    크다
4    크다
dtype: object


In [332]:
result = s.apply(lambda x:'크다'if x >= 13 else '작다')
print(result)

0    작다
1    크다
2    작다
3    크다
4    크다
dtype: object


# 필터링

In [334]:
data = [42500, 42550, 41800, 42550, 42650]
index = ['2019-05-31', '2019-05-30', '2019-05-29', '2019-05-28', '2019-05-27']
s = pd.Series(data=data, index=index)
s

2019-05-31    42500
2019-05-30    42550
2019-05-29    41800
2019-05-28    42550
2019-05-27    42650
dtype: int64

In [337]:
cond = s > 42000
print(cond)

2019-05-31     True
2019-05-30     True
2019-05-29    False
2019-05-28     True
2019-05-27     True
dtype: bool


In [338]:
s [cond]

2019-05-31    42500
2019-05-30    42550
2019-05-28    42550
2019-05-27    42650
dtype: int64

In [339]:
s[s > 42000]

2019-05-31    42500
2019-05-30    42550
2019-05-28    42550
2019-05-27    42650
dtype: int64

In [355]:
from pandas import Series

close = [42500, 42550, 41800, 42550, 42650]
open = [42600, 42200, 41850, 42550, 42500]
index = ['2019-05-31', '2019-05-30', '2019-05-29', '2019-05-28', '2019-05-27']

open = Series(data=open, index=index)
close = Series(data=close, index=index)

close[close > open]
# 문제: 종가가 시가보다 높은 날을 구하세요.

2019-05-30    42550
2019-05-27    42650
dtype: int64